var radar_data = [{"name":"Database based Integration", "pc":{"r":350,"t":135},"movement":"t"},
    {"name":"Scrum certification", "pc":{"r":350,"t":95},"movement":"c"},
    {"name":"Incremental data warehousing", "pc":{"r":250,"t":165},"movement":"c"},    
    {"name":"DevOps", "pc":{"r":250,"t":110},"movement":"c"},    
    {"name":"Polygot Programming", "pc":{"r":180,"t":170},"movement":"c"},    
    {"name":"Automation of technical tests", "pc":{"r":180,"t":155},"movement":"c"},    
{"name":"Capability modelling", "pc":{"r":180,"t":125},"movement":"c"},   
{"name":"Service choreography", "pc":{"r":180,"t":105},"movement":"c"},   
{"name":"Continuous deployment", "pc":{"r":180,"t":100},"movement":"c"},   
{"name":"Evolutionary architecture", "pc":{"r":120,"t":95},"movement":"c"},   
{"name":"Coding architects", "pc":{"r":90,"t":170},"movement":"c"},   
{"name":"Visualisation and metrics", "pc":{"r":80,"t":150},"movement":"c"},   
{"name":"Web as platform", "pc":{"r":80,"t":110},"movement":"c"},   
{"name":"Emergent design", "pc":{"r":80,"t":100},"movement":"c"},   
{"name":"Evolutionary database", "pc":{"r":70,"t":170},"movement":"c"},   
{"name":"Platform roadmaps", "pc":{"r":30,"t":100},"movement":"c"},   
{"name":"Build pipelines", "pc":{"r":30,"t":160},"movement":"c"},   
{"name":"ESB", "pc":{"r":390,"t":20},"movement":"t"},   
{"name":"Intentional Programming", "pc":{"r":310,"t":10},"movement":"c"},   
{"name":"Cross mobile platforms", "pc":{"r":280,"t":85},"movement":"c"},   
{"name":"Github", "pc":{"r":280,"t":70},"movement":"c"},   
{"name":"Restfulie", "pc":{"r":280,"t":50},"movement":"c"},   
{"name":"RDF triple stores", "pc":{"r":280,"t":30},"movement":"c"},   
{"name":"Apache camel", "pc":{"r":180,"t":85},"movement":"c"},   
{"name":"Next gen test tools", "pc":{"r":180,"t":75},"movement":"c"},   
{"name":"NoSQL", "pc":{"r":180,"t":65},"movement":"c"},   
{"name":"Neo4j", "pc":{"r":180,"t":50},"movement":"c"},   
{"name":"Message busses without smarts", "pc":{"r":160,"t":85},"movement":"c"},   
{"name":"Puppet", "pc":{"r":130,"t":85},"movement":"c"},   
{"name":"mongoDB", "pc":{"r":130,"t":55},"movement":"c"},   
{"name":"Mercurial", "pc":{"r":130,"t":30},"movement":"c"},   
{"name":"Git", "pc":{"r":130,"t":15},"movement":"c"},   
{"name":"Squid", "pc":{"r":80,"t":85},"movement":"c"},   
{"name":"ASP.NET MVC", "pc":{"r":80,"t":10},"movement":"c"},   
{"name":"Subversion", "pc":{"r":30,"t":30},"movement":"c"},   
{"name":"Java language end of life", "pc":{"r":290,"t":355},"movement":"c"},   
{"name":"F#", "pc":{"r":270,"t":330},"movement":"c"},   
{"name":"Scala", "pc":{"r":290,"t":320},"movement":"c"},   
{"name":"Clojure", "pc":{"r":260,"t":310},"movement":"c"},   
{"name":"HTML 5", "pc":{"r":250,"t":275},"movement":"c"},   
{"name":"DSLs", "pc":{"r":190,"t":340},"movement":"c"},   
{"name":"Groovy", "pc":{"r":190,"t":280},"movement":"c"},   
{"name":"C#4", "pc":{"r":90,"t":355},"movement":"c"},   
{"name":"JRuby", "pc":{"r":90,"t":330},"movement":"c"},   
{"name":"Javascript as a 1st class language", "pc":{"r":90,"t":275},"movement":"c"},   
{"name":"Ruby", "pc":{"r":30,"t":282},"movement":"c"},   
{"name":"Rich internet applications", "pc":{"r":390,"t":265},"movement":"c"},   
{"name":"GWT", "pc":{"r":390,"t":250},"movement":"c"},   
{"name":"IE8", "pc":{"r":390,"t":230},"movement":"c"},   
{"name":"WS-* beyond basic profile", "pc":{"r":390,"t":190},"movement":"c"},   
{"name":"Azure", "pc":{"r":290,"t":265},"movement":"c"},   
{"name":"Mobile Web", "pc":{"r":275,"t":260},"movement":"t"},   
{"name":"Google App Engine", "pc":{"r":290,"t":255},"movement":"c"},   
{"name":"Application appliances", "pc":{"r":190,"t":245},"movement":"c"},   
{"name":"Google as corporate platform", "pc":{"r":290,"t":200},"movement":"c"},   
{"name":"GPGPU", "pc":{"r":190,"t":185},"movement":"t"},   
{"name":"App containers", "pc":{"r":250,"t":260},"movement":"c"},   
{"name":"OAuth", "pc":{"r":130,"t":260},"movement":"t"},   
{"name":"RDFa", "pc":{"r":130,"t":250},"movement":"t"},   
{"name":"Location based services", "pc":{"r":130,"t":230},"movement":"c"},   
{"name":"iPad", "pc":{"r":130,"t":220},"movement":"c"},   
{"name":"EC2 & S3", "pc":{"r":190,"t":250},"movement":"c"},   
{"name":"Facebook as a business platform", "pc":{"r":190,"t":190},"movement":"c"},   
{"name":"JVM as platform", "pc":{"r":90,"t":265},"movement":"c"},   
{"name":"iPhone", "pc":{"r":90,"t":215},"movement":"c"},   
{"name":"Android", "pc":{"r":90,"t":190},"movement":"c"},   
{"name":"KVM", "pc":{"r":70,"t":260},"movement":"t"},   
{"name":"Atom", "pc":{"r":70,"t":245},"movement":"t"},   
{"name":"ALT.NET", "pc":{"r":90,"t":190},"movement":"c"},   
{"name":"IE6 End of Life", "pc":{"r":30,"t":225},"movement":"c"}     
];

//left to right -> top to bottom
var radar_quadrants = [
{"name":"Techniques", "start":0, "end":17},
{"name":"Tools", "start":17, "end":35},
{"name":"Platforms", "start":47, "end":70},
{"name":"Languages", "start":35, "end":46}
];
//
var radar_arcs = [{'r':100,'name':'Adopt'},{'r':200,'name':'Trial'},{'r':300,'name':'Assess'},{'r':400,'name':'Hold'}];

var radar_title = "ThoughtWorks Technology Radar (Aug 2010)";